name: CI/CD Pipeline


on: // trigger
  push:
    branches:
      - master


jobs: // job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Lay Code // step 1
        uses: actions/checkout@v3


      - name: 🚀 Day Code Len VPS // step 2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.VPS_USERNAME }}/sample-project"


      - name: 🔄 Restart Server // step 3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/sample-project
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
