name: CI/CD Pipeline Mini Game

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Lấy Code
        uses: actions/checkout@v3

      - name: 🚀 Đẩy Code Lên VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          # LỖI 1: Cố tình viết sai biến VPS_USERNAME thành VPS_USERNAMEE
          username: ${{ secrets.VPS_USERNAMEE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.VPS_USERNAME }}/sample-project"

      - name: 🔄 Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/sample-project
            # Cài thư viện
            npm install
            # Khởi động app (dùng ecosystem.config.js để lấy PORT đúng)
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
